add skywalking metric images
higress-group/higress-group.github.io pull request #148
Opened 2023-06-20 13:08 UTC by 2456868764

2023-06-25 01:22 UTC, CH3CHO requested changes

2023-06-25 01:22 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/skywalking.md
>  本文介绍 Higress 集成 Skwywalking 实现可观测性，主要内容涉及整体架构，Skywalking 调用链路跟踪原理，Higress架构，Higress本地测试环境搭建，Higress 配置，业务应用安装, 调用链路跟踪配置和 Higress gateway 指标展示等内容。
拼写错误，麻烦一并修正

2023-06-25 01:22 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/skywalking.md
> +这次可观测性探索相关 manifests [下载地址](../../../static/img/blog/skywalking/skywalking.zip)
zip 文件放 img 目录下面是不是不太好？

2023-06-25 01:43 UTC, 2456868764 commented on i18n/zh-cn/docusaurus-plugin-content-blog/skywalking.md
>  本文介绍 Higress 集成 Skwywalking 实现可观测性，主要内容涉及整体架构，Skywalking 调用链路跟踪原理，Higress架构，Higress本地测试环境搭建，Higress 配置，业务应用安装, 调用链路跟踪配置和 Higress gateway 指标展示等内容。
OK

2023-06-25 01:44 UTC, 2456868764 commented on i18n/zh-cn/docusaurus-plugin-content-blog/skywalking.md
> +这次可观测性探索相关 manifests [下载地址](../../../static/img/blog/skywalking/skywalking.zip)
zip 文件位置有什么好建议？

2023-06-25 02:06 UTC, johnlanni commented on i18n/zh-cn/docusaurus-plugin-content-blog/skywalking.md
> +这次可观测性探索相关 manifests [下载地址](../../../static/img/blog/skywalking/skywalking.zip)
是的，相关提供下载的配置文件建议放到个人的github gist上 @2456868764

2023-06-25 02:34 UTC, 2456868764 commented on i18n/zh-cn/docusaurus-plugin-content-blog/skywalking.md
> +这次可观测性探索相关 manifests [下载地址](../../../static/img/blog/skywalking/skywalking.zip)
github gist 访问不了， 这个 https://gitcode.net/-/snippets/3612 可以吗？

2023-06-25 03:03 UTC, 2456868764 commented on i18n/zh-cn/docusaurus-plugin-content-blog/skywalking.md
> +这次可观测性探索相关 manifests [下载地址](../../../static/img/blog/skywalking/skywalking.zip)
已经更新

2023-06-25 03:04 UTC, 2456868764 commented
已经更新， 麻烦再看一下

2023-06-25 04:31 UTC, CH3CHO requested changes

2023-06-25 04:31 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/skywalking.md
> +本文介绍 Higress 集成 Skywalking 实现可观测性, 主要内容涉及整体架构, Skywalking 调用链路跟踪原理, Higress 架构, 业务应用集成 Skywalking, 本地测试环境搭建, Higress 配置, 应用安装, 调用链路跟踪配置以及 Higress gateway 指标和监控面板。
中文文档还是要用中文标点的。

2023-06-25 05:42 UTC, 2456868764 commented on i18n/zh-cn/docusaurus-plugin-content-blog/skywalking.md
> +本文介绍 Higress 集成 Skywalking 实现可观测性, 主要内容涉及整体架构, Skywalking 调用链路跟踪原理, Higress 架构, 业务应用集成 Skywalking, 本地测试环境搭建, Higress 配置, 应用安装, 调用链路跟踪配置以及 Higress gateway 指标和监控面板。
已经更新

2023-06-25 05:55 UTC, johnlanni commented on i18n/zh-cn/docusaurus-plugin-content-blog/skywalking.md
> +这次可观测性探索相关 manifests [下载地址](../../../static/img/blog/skywalking/skywalking.zip)
可以的

2023-06-25 08:56 UTC, 2456868764 commented
i'v updated ,pls review it again.

2023-06-26 00:10 UTC, CH3CHO approved these changes

2023-06-26 01:40 UTC, merged