Add AI plugin PR
higress-group/higress-group.github.io pull request #157
Opened 2023-07-12 08:12 UTC by vikizhao156

Add AI plugin PR

2023-07-12 08:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/higress-group/higress-group.github.io?pullRequest=157) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/higress-group/higress-group.github.io?pullRequest=157) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/higress-group/higress-group.github.io?pullRequest=157) it.</sub>

2023-07-12 09:21 UTC, CH3CHO reviewed
先看了一遍中文版部分。除了行内评论外，多张图片下面的标题显示有问题。建议本地运行调整一下。

2023-07-12 09:21 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/Power AIGC Applications with Higress.md
> +以ChatGPT为代表的AIGC技术为企业生产带来了巨大的变化，并一直在企业应用开发领域占据一席之地。AI大模型凭借其强大的学习能力，帮助企业人员能完成各种复杂的任务，例如帮助开发人员编写、调试和记录代码、研究人员快速了解科研领域、营销人员撰写产品描述、设计人员设计新作品等等。许多企业探索AI大模型的应用方法和对外服务方法，通过网关进行AI大模型的API管理成为了很常规的需求。
建议加一下元数据信息，这样可以显示出中文的标题和作者信息。

参考；https://github.com/higress-group/higress-group.github.io/blob/main/i18n/zh-cn/docusaurus-plugin-content-blog/nacos.md?plain=1#L1

2023-07-12 09:21 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/Power AIGC Applications with Higress.md
> +以ChatGPT为代表的AIGC技术为企业生产带来了巨大的变化，并一直在企业应用开发领域占据一席之地。AI大模型凭借其强大的学习能力，帮助企业人员能完成各种复杂的任务，例如帮助开发人员编写、调试和记录代码、研究人员快速了解科研领域、营销人员撰写产品描述、设计人员设计新作品等等。许多企业探索AI大模型的应用方法和对外服务方法，通过网关进行AI大模型的API管理成为了很常规的需求。
“帮助企业人员能完成各种复杂的任务”，读起来怪怪的

2023-07-12 09:21 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/Power AIGC Applications with Higress.md
> +                                           <center>图1. OpenAI API部分模型计费标准</center>
这里显示上好像有点问题？

![image](https://github.com/higress-group/higress-group.github.io/assets/2909796/bf8c57d8-eadd-4d9a-9ff3-3304f47f4ddc)

2023-07-12 09:21 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/Power AIGC Applications with Higress.md
> +以OpenAI为例，OpenAI的API调用并不是基于请求量或者订阅时间来计费，而是基于每个请求的使用量来计费。对于AI大模型来说，模型输入与输出的字符数（tokens）可以比较好的衡量当前模型进行推理任务的复杂度。因此基于token作为请求使用量进行计费是OpenAPI的标准计费策略。对于不同的模型tokens的计费标准也不同，更复杂的模型会生成更好的结果，但也会带来更高的计费。OpenAI通
AI领域里的Token应该不是字符的意思吧？

2023-07-12 09:21 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/Power AIGC Applications with Higress.md
> + 下面我们将以Higress对接OpenAI大语言模型为例，介绍Higress如何无缝对接AI大模型。整体方案如图3所示，我们基于WASM拓展了Higress插件，实现了对OpenAI语言模型的请求代理转发。基于Higress提供的Key-Auth认证插件的能力，我们实现统一API-Key下的多租户认证。基于Higress提供的Request-Block请求过滤的能力，我们将实现含敏感信息的请求
整篇文档的空格和空行策略我觉得都比较奇怪。有的时候空很多，有的时候又不空。有的段落前面空一格，有的空好几格，有的又不空格。建议统一。

2023-07-12 09:21 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/Power AIGC Applications with Higress.md
> +2. 部署Go语言开发WASM插件的开发环境，参考[使用 GO 语言开发 WASM 插件 | Higress](https://higress.io/zh-cn/docs/user/wasm-go)。
“环境”前面一般用“准备”比较好吧

2023-07-12 09:21 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/Power AIGC Applications with Higress.md
> +"stop": [" %s", " %s"]
这两个%s前面是必须要有个空格的吗？

2023-07-12 09:21 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/Power AIGC Applications with Higress.md
> +	body := fmt.Sprintf(bodyTemplate, config.Model, prompt[0], config.HumainId, config.AIId)
HumainId or HumanId?

2023-07-12 09:25 UTC, johnlanni commented on i18n/zh-cn/docusaurus-plugin-content-blog/Power AIGC Applications with Higress.md
> +"stop": [" %s", " %s"]
这个是参考的 openai 的文档，应该不是必须的，没仔细研究过

2023-07-12 09:31 UTC, CH3CHO commented
另外，中英文共有的问题麻烦一并修改。这部分在英文部分将不再单独标注。

2023-07-12 09:35 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/Power AIGC Applications with Higress.md
> +"stop": [" %s", " %s"]
根据 OpenAI 自己文档里的例子，应该是不需要的。这里是不是验证一下，没问题的话就去掉比较好？

https://platform.openai.com/docs/api-reference/completions/create
![image](https://github.com/higress-group/higress-group.github.io/assets/2909796/973dbfd2-5120-4bf3-81be-e720010aebf2)

2023-07-12 09:42 UTC, CH3CHO requested changes

2023-07-12 09:57 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/Power AIGC Applications with Higress.md
> +以ChatGPT为代表的AIGC技术为企业生产带来了巨大的变化，并一直在企业应用开发领域占据一席之地。AI大模型凭借其强大的学习能力，帮助企业人员能完成各种复杂的任务，例如帮助开发人员编写、调试和记录代码、研究人员快速了解科研领域、营销人员撰写产品描述、设计人员设计新作品等等。许多企业探索AI大模型的应用方法和对外服务方法，通过网关进行AI大模型的API管理成为了很常规的需求。
而且加了这个之后，文件名也不需要搞这么复杂了

2023-07-12 10:59 UTC, vikizhao156 commented
> 先看了一遍中文版部分。除了行内评论外，多张图片下面的标题显示有问题。建议本地运行调整一下。

收到，感谢回复

2023-07-12 11:12 UTC, johnlanni commented on i18n/zh-cn/docusaurus-plugin-content-blog/Power AIGC Applications with Higress.md
> +"stop": [" %s", " %s"]
貌似 openai 的文档更新了，嗯可以把空格去掉

2023-07-13 04:11 UTC, CH3CHO requested changes

2023-07-13 04:11 UTC, CH3CHO commented on i18n/en-us/docusaurus-plugin-content-blog/ai_plugin.md
> +For organizations, observing and analyzing the usage of large AI model calls for each user helps to understand their usage and costs. It is also necessary for individual users to understand their own
这里的指标不应该翻译为"indicators"，应该是"metrics"

2023-07-13 04:11 UTC, CH3CHO commented on i18n/en-us/docusaurus-plugin-content-blog/ai_plugin.md
> +Taking the observation of each user's usage of the OPENAI-Curie model as an example, the administrator can set the observability parameter in the request header：x-mse-consumer, to distinguish users t
**MSE console** - **cloud native gateway** - **gateway instance** - **parameter configurator**- **Custom format**

上面这一行的大小写和阿里云控制台的实际大小写一致吗？

2023-07-13 04:21 UTC, CH3CHO commented on i18n/en-us/docusaurus-plugin-content-blog/ai_plugin.md
> +Based on rich plugin capabilities, Higress provides functions such as authentication, request filtering, traffic control, usage monitoring, and security protection, helping organizations interact wit
“Commercial Higress”之间疑似是两个空格

2023-07-13 04:21 UTC, CH3CHO commented on i18n/en-us/docusaurus-plugin-content-blog/ai_plugin.md
> +We will take Higress connecting to the OpenAI API as an example to introduce how Higress seamlessly connects to the large AI model. The overall solution is shown in Fig.3. We have extended the Higres
`Based on the Request-Block` 后面是不是加个 plugin 好一点？

2023-07-13 04:21 UTC, CH3CHO commented on i18n/en-us/docusaurus-plugin-content-blog/ai_plugin.md
> +1. Install Higress. Please refer to [Deploy Higress By Helm | Higress](https://higress.io/en-us/docs/ops/deploy-by-helm/).
"| Higress" 是不是没啥必要加在这里呢？中文同理

2023-07-14 06:56 UTC, vikizhao156 commented
感谢回复，上述意见已采纳并完成修改。

2023-07-14 07:14 UTC, CH3CHO reviewed
先仔细阅读了中文的第一段。详情请见行内评论。

2023-07-14 07:14 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +以ChatGPT为代表的AIGC技术为企业生产带来了巨大的变化，并一直在企业应用开发领域占据一席之地。AI大模型凭借其强大的学习能力，帮助人们完成各种复杂的任务，例如帮助开发人员编写、调试和记录代码、研究人员快速了解科研领域、营销人员撰写产品描述、设计人员设计新作品等等。许多企业探索如何降低AI大模型的使用成本，通过网关进行AI大模型的API管理成为了很常规的需求。
许多企业探索如何降低AI大模型的使用成本，通过网关进行AI大模型的API管理成为了很常规的需求。

这一句前后两段的连接很奇怪，感觉是个因果关系，但并没有相应的词语将其表现出来。

2023-07-14 07:14 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +以ChatGPT为代表的AIGC技术为企业生产带来了巨大的变化，并一直在企业应用开发领域占据一席之地。AI大模型凭借其强大的学习能力，帮助人们完成各种复杂的任务，例如帮助开发人员编写、调试和记录代码、研究人员快速了解科研领域、营销人员撰写产品描述、设计人员设计新作品等等。许多企业探索如何降低AI大模型的使用成本，通过网关进行AI大模型的API管理成为了很常规的需求。
并一直在企业应用开发领域占据一席之地：这个“一直”怎么解释呢？前面说“带来了巨大的变化”，说明是个新事物，那怎么能一直呢？有点奇怪

2023-07-14 13:49 UTC, CH3CHO requested changes
中文内容过了一遍，详见行内日志。如有疑问，我们可以进行讨论。

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +以OpenAI为例，OpenAI的API调用并不是基于请求量或者订阅时间来计费，而是基于每个请求的使用量来计费。对于AI大模型来说，模型输入与输出的token数可以比较好的衡量当前模型进行推理任务的复杂度。因此基于token作为请求使用量进行计费是OpenAPI的标准计费策略。对于不同的模型token的计费标准也不同，更复杂的模型会生成更好的结果，但也会带来更高的计费。OpenAI通过为用户分发
“更复杂的模型会生成更好的结果”：这里更字的用法怪怪的。

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +以OpenAI为例，OpenAI的API调用并不是基于请求量或者订阅时间来计费，而是基于每个请求的使用量来计费。对于AI大模型来说，模型输入与输出的token数可以比较好的衡量当前模型进行推理任务的复杂度。因此基于token作为请求使用量进行计费是OpenAPI的标准计费策略。对于不同的模型token的计费标准也不同，更复杂的模型会生成更好的结果，但也会带来更高的计费。OpenAI通过为用户分发
OpenAI通过为用户分发API密钥来完成用户的鉴权与收费等功能：这句话弯转的有点快，衔接的比较生硬。

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +对于组织来说，为每位成员申请AI大模型访问权限（API Key）显然是不现实的。分散的API密钥将不利于组织进行API的用量计算、管理与付费，从而增加AI大模型的使用成本。其次，对于组织来说，AI模型的选型、使用频率和成员使用权限、以及向AI大模型暴露哪些数据都是比较重要的管理功能。
为每位成员申请AI大模型（加个“的”是不是好一些？）访问权限

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +对于组织来说，为每位成员申请AI大模型访问权限（API Key）显然是不现实的。分散的API密钥将不利于组织进行API的用量计算、管理与付费，从而增加AI大模型的使用成本。其次，对于组织来说，AI模型的选型、使用频率和成员使用权限、以及向AI大模型暴露哪些数据都是比较重要的管理功能。
都是比较重要的管理功能：是不是改成“在管理中需要着重关注的功能”更好一些

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +Higress基于丰富的插件能力，提供认证鉴权、请求过滤、流量控制、用量监测和安全防护等功能，帮助组织与AI大模型的API交互变得更加安全、可靠和可观察。基于Higress提供的认证鉴权能力，组织可以实现通过统一的API密钥进行AI模型的调用量管理和付费等，并为团队成员授予不同的AI模型访问权限；基于Higress提供的流量控制能力，组织能为不同的模型与用户设置差异化的访问速率限制，有效降低AI
提供（要不要加个“了”？）认证鉴权

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +Higress基于丰富的插件能力，提供认证鉴权、请求过滤、流量控制、用量监测和安全防护等功能，帮助组织与AI大模型的API交互变得更加安全、可靠和可观察。基于Higress提供的认证鉴权能力，组织可以实现通过统一的API密钥进行AI模型的调用量管理和付费等，并为团队成员授予不同的AI模型访问权限；基于Higress提供的流量控制能力，组织能为不同的模型与用户设置差异化的访问速率限制，有效降低AI
帮助组织与AI大模型的：前面要不要加个“能够”？

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +Higress基于丰富的插件能力，提供认证鉴权、请求过滤、流量控制、用量监测和安全防护等功能，帮助组织与AI大模型的API交互变得更加安全、可靠和可观察。基于Higress提供的认证鉴权能力，组织可以实现通过统一的API密钥进行AI模型的调用量管理和付费等，并为团队成员授予不同的AI模型访问权限；基于Higress提供的流量控制能力，组织能为不同的模型与用户设置差异化的访问速率限制，有效降低AI
组织可以实现通过统一的API密钥进行AI模型的调用量管理和付费等：这个“等”字结束的好突兀

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +Higress基于丰富的插件能力，提供认证鉴权、请求过滤、流量控制、用量监测和安全防护等功能，帮助组织与AI大模型的API交互变得更加安全、可靠和可观察。基于Higress提供的认证鉴权能力，组织可以实现通过统一的API密钥进行AI模型的调用量管理和付费等，并为团队成员授予不同的AI模型访问权限；基于Higress提供的流量控制能力，组织能为不同的模型与用户设置差异化的访问速率限制，有效降低AI
可观察。基于：这个句号要不要换成冒号？

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +Higress基于丰富的插件能力，提供认证鉴权、请求过滤、流量控制、用量监测和安全防护等功能，帮助组织与AI大模型的API交互变得更加安全、可靠和可观察。基于Higress提供的认证鉴权能力，组织可以实现通过统一的API密钥进行AI模型的调用量管理和付费等，并为团队成员授予不同的AI模型访问权限；基于Higress提供的流量控制能力，组织能为不同的模型与用户设置差异化的访问速率限制，有效降低AI
开箱即用的...日志系统的能力：日志系统不算是能力吧，日志记录更好一些吧？

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +下文将给出基于Higress与WASM实现的AI大模型API代理插件方案。Higress支持基于WASM实现对外扩展的能力。WASM插件提供的多语言生态和热插拔机制为插件的实现和部署提供便利。Higress同时支持在插件中请求外部服务，为AI代理插件的实现提供了高效的解决路径。
WASM插件提供的多语言生态和热插拔机制为插件的实现和部署提供（“了”）便利

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +我们给出OpenAI-API的代理插件的实现示例，详情请参考[AI proxy plugin](https://github.com/alibaba/higress/tree/main/plugins/wasm-go/extensions/chatgpt-proxy)。下列代码实现了插件相关配置完成之后，基于HTTP自动将请求代理转发到OPENAI-API，具体实现步骤如下：
下列代码实现了插件相关配置完成之后，基于HTTP自动将请求代理转发到OPENAI-API：读起来感觉很奇怪，似乎少个结尾

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +1. 通过RouteCluster方法指定具体的OPENAI-API的host,确认用户请求转发的具体路径，并新建用于请求代理转发的HTTP Client。
发现了英文标点

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +2. 对用户请求进行OPENAI-API的格式封装，通过HTTP Client进行请求转发与响应接受，并将响应转发给用户。
OPENAI-API 的大小写和连字符使用全文应保持一致

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +2. 对用户请求进行OPENAI-API的格式封装，通过HTTP Client进行请求转发与响应接受，并将响应转发给用户。
进行请求转发与响应接受：“响应接受”的说法怪怪的

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +}
这段 JSON 要不要缩进一下？

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +本示例提供已经编译好的AI-proxy-plugin-wasm文件并完成对应docker镜像的构建和推送，推荐配置如下所示：
提供已经编译好的AI-proxy-plugin-wasm文件并完成对应docker镜像的构建和推送：说法很奇怪，比较机翻

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +根据该配置，网关代理到OpenAI API下的curie模型，用户通过text关键字在url中输入文本。
网关代理到OpenAI API下的curie模型，用户通过text关键字在url中输入文本：机翻严重

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +curl "http://{GatewayIP}/?text=Say,hello"
不需要 Host 吗？

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +不同于为每位成员颁发AI-API密钥的形式，企业可以基于Higress网关提供的认证鉴权能力，依靠内部授权（如Key Auth等）来管理成员对AI模型对访问权限，从而限制成员可以使用的服务和模型，并依靠统一的AI-API密钥进行请求代理转发实现对API用量的统一管理。接下来以key_auth为例介绍基于Higress的多租户认证能力。
AI-API：这个连字符链接的是AI和API，还是AI和API密钥？

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +不同于为每位成员颁发AI-API密钥的形式，企业可以基于Higress网关提供的认证鉴权能力，依靠内部授权（如Key Auth等）来管理成员对AI模型对访问权限，从而限制成员可以使用的服务和模型，并依靠统一的AI-API密钥进行请求代理转发实现对API用量的统一管理。接下来以key_auth为例介绍基于Higress的多租户认证能力。
key_auth 的拼写在全文建议保持一致

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +不同于为每位成员颁发AI-API密钥的形式，企业可以基于Higress网关提供的认证鉴权能力，依靠内部授权（如Key Auth等）来管理成员对AI模型对访问权限，从而限制成员可以使用的服务和模型，并依靠统一的AI-API密钥进行请求代理转发实现对API用量的统一管理。接下来以key_auth为例介绍基于Higress的多租户认证能力。
基于Higress的多租户认证能力：感觉这个“基于Higress”的说法比较奇怪

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +以上配置定义了指向AI模型服务的消费者组consumers，并且只有consumer1具备访问当前路由下AI模型服务的权限。
consumers 标注为代码吧，consumer 1 同理

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +#根据请求提供的 API Key匹配到的调用者无AI模型服务的访问权限，返回403
为啥 API Key 前面要空格。英文单词与中文之间的空格使用请在全文内保持一致

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +Higress除了提供网关级多租户认证外，提供限流等能力。Key Rate Limit插件可以根据用户在消费组中的成员资格对用户应用速率进行限制，从而限制关键应用程序对高成本AI大模型服务的消耗。基于多租户认证插件与限流等功能插件能力，Higress可以完全控制AI大模型API的访问权限、访问数量与调用成本。
前面用了“除了”，后面应该还有个连词吧。

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +Higress除了提供网关级多租户认证外，提供限流等能力。Key Rate Limit插件可以根据用户在消费组中的成员资格对用户应用速率进行限制，从而限制关键应用程序对高成本AI大模型服务的消耗。基于多租户认证插件与限流等功能插件能力，Higress可以完全控制AI大模型API的访问权限、访问数量与调用成本。
用户应用速率：感觉没有这种说法吧

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +Higress除了提供网关级多租户认证外，提供限流等能力。Key Rate Limit插件可以根据用户在消费组中的成员资格对用户应用速率进行限制，从而限制关键应用程序对高成本AI大模型服务的消耗。基于多租户认证插件与限流等功能插件能力，Higress可以完全控制AI大模型API的访问权限、访问数量与调用成本。
关键应用程序：非关键应用程序就不需要限制了吗？

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +Higress除了提供网关级多租户认证外，提供限流等能力。Key Rate Limit插件可以根据用户在消费组中的成员资格对用户应用速率进行限制，从而限制关键应用程序对高成本AI大模型服务的消耗。基于多租户认证插件与限流等功能插件能力，Higress可以完全控制AI大模型API的访问权限、访问数量与调用成本。
基于多租户认证插件与限流等功能插件能力：不通顺吧

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +对于AI大模型尤其是语言模型来说，要得到良好的返回往往需要用户提供足够的提示（prompt）作为模型输入。这也意味着组织和个人可能会在提供提示的过程中面临数据泄漏的风险。因此如何在使用AI模型的过程中保障数据安全也是API调用方面临重要问题。保护数据安全涉及到对AI模型的API调用渠道进行严格的控制。一种方式是使用特定的经批准的模型与其发布的API。另一种方式是对含敏感信息的用户请求进行拦截。这
request block 的拼写在全文应保持一致

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +对于AI大模型尤其是语言模型来说，要得到良好的返回往往需要用户提供足够的提示（prompt）作为模型输入。这也意味着组织和个人可能会在提供提示的过程中面临数据泄漏的风险。因此如何在使用AI模型的过程中保障数据安全也是API调用方面临重要问题。保护数据安全涉及到对AI模型的API调用渠道进行严格的控制。一种方式是使用特定的经批准的模型与其发布的API。另一种方式是对含敏感信息的用户请求进行拦截。这
前面“既能”，后面感觉少点什么吧

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +Request Block插件实现了基于URL、请求头等特征屏蔽HTTP请求，可以用于防护部分站点资源不对外部暴露。 通过在**Higress控制台**-**插件市场-Request Block**进行屏蔽字段配置，即可防止含敏感字段的请求对外发送。
实现了基于URL、请求头等特征屏蔽HTTP请求：实现这个动词的宾语是什么

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +Request Block插件实现了基于URL、请求头等特征屏蔽HTTP请求，可以用于防护部分站点资源不对外部暴露。 通过在**Higress控制台**-**插件市场-Request Block**进行屏蔽字段配置，即可防止含敏感字段的请求对外发送。
可以用于防护部分站点资源不对外部暴露：防护的宾语是什么

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +以上配置定义了当前路由下基于URL的屏蔽字段，其中含敏感信息的请求如password、pw将被屏蔽。
其中含敏感信息的请求如password、pw将被屏蔽：这个“如”针对的是哪个词，跟在请求后面是否合理？

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +对于组织来说，进行对各用户进行AI模型调用的用量观测和分析有助于了解其使用情况与产生的成本。对于个人用户了解自己的调用量和开销也是必要的。因此，在网关层进行调用的观测和分析对于AI大模型的API管理是必要的能力。[商业版Higress](https://www.alibabacloud.com/product/microservices-engine?spm=higress-website.to
进行对各用户进行AI模型调用的用量观测和分析：两个“进行”？

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +对于组织来说，进行对各用户进行AI模型调用的用量观测和分析有助于了解其使用情况与产生的成本。对于个人用户了解自己的调用量和开销也是必要的。因此，在网关层进行调用的观测和分析对于AI大模型的API管理是必要的能力。[商业版Higress](https://www.alibabacloud.com/product/microservices-engine?spm=higress-website.to
对于个人用户：要不要加个逗号在后面？

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +对于组织来说，进行对各用户进行AI模型调用的用量观测和分析有助于了解其使用情况与产生的成本。对于个人用户了解自己的调用量和开销也是必要的。因此，在网关层进行调用的观测和分析对于AI大模型的API管理是必要的能力。[商业版Higress](https://www.alibabacloud.com/product/microservices-engine?spm=higress-website.to
在网关层进行调用的观测和分析对于AI大模型的API管理是必要的能力：感觉很机翻

2023-07-14 13:49 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +Higress团队在[Higress控制台样例](http://demo.higress.io/route)上部署了基于GPT模型的彩蛋聊天机器人，如果在使用Higress过程中有问题欢迎向它提问！
这个链接可以考虑把尾巴上的 /route 去掉

2023-07-14 13:50 UTC, CH3CHO requested changes
中文内容过了一遍，详见行内日志。如有疑问，我们可以进行讨论。

2023-07-17 05:41 UTC, vikizhao156 commented on i18n/zh-cn/docusaurus-plugin-content-blog/ai_plugin.md
> +不同于为每位成员颁发AI-API密钥的形式，企业可以基于Higress网关提供的认证鉴权能力，依靠内部授权（如Key Auth等）来管理成员对AI模型对访问权限，从而限制成员可以使用的服务和模型，并依靠统一的AI-API密钥进行请求代理转发实现对API用量的统一管理。接下来以key_auth为例介绍基于Higress的多租户认证能力。
这里是采用AI-API的说法是为了区分OpenAI-API密钥与网关内部API密钥

2023-07-17 05:59 UTC, CH3CHO commented on i18n/en-us/docusaurus-plugin-content-blog/ai_plugin.md
> +It is unrealistic for an organization to apply for an API Key for each member. Scattered API keys will not be conducive to the organization's calculation, management, and payment of API usage, thereb
the use rights of members：中文原文为“成员使用权限”，这样翻译的有点奇怪，可以考虑使用 access permissions。

2023-07-17 05:59 UTC, CH3CHO commented on i18n/en-us/docusaurus-plugin-content-blog/ai_plugin.md
> +Based on rich plugin capabilities, Higress provides functions such as authentication, request filtering, traffic control, usage monitoring, and security protection, helping organizations interact wit
, based on the **request interception*：这里应该是分号吧，前面就是分号

2023-07-19 06:43 UTC, merged