doc:DeployingonWindows
higress-group/higress-group.github.io pull request #165
Opened 2023-07-27 02:06 UTC by Fkbqf

Please let me know if there is any problem, I will modify it in time

2023-07-27 02:07 UTC, johnlanni requested changes

2023-07-27 02:07 UTC, johnlanni commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/user/DeployOnWindows.md
> +#### 安装Nacos
这里改成安装 Higress，Nacos安装单独搞一节，建议用Nacos官网的安装模式，不用这个内置的Nacos

2023-07-27 02:12 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/user/DeployOnWindows.md
> +title: window利用Nacos部署higress
Windows，不是window，而且W应该大写

2023-07-27 02:12 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/user/DeployOnWindows.md
> +### 下载docker-desktop
Docker Desktop前后的拼写应保持一致

2023-07-27 02:12 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/user/DeployOnWindows.md
> +####  配置wsl2
WSL的前后大小写应保持一致

2023-07-27 02:12 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/user/DeployOnWindows.md
> +# 验证Cygwin安装是否成功
这个标题级别怎么突然乱了？

2023-07-27 02:12 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/user/DeployOnWindows.md
> +**访问http://localhost:8080/,使用 admin 作为用户名密码登录 Higress 控制台。**
这个链接最好处理一下，自动识别的会有问题

![Uploading image.png…]()

2023-07-27 02:12 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/user/DeployOnWindows.md
> +title: window利用Nacos部署higress
Higress的大小写也前后保持一致吧

2023-07-28 01:43 UTC, johnlanni approved these changes

2023-07-28 01:43 UTC, merged