add blog for e2e debug
higress-group/higress-group.github.io pull request #195
Opened 2023-12-19 03:49 UTC by sjcsjc123

2023-12-19 03:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/higress-group/higress-group.github.io?pullRequest=195) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/higress-group/higress-group.github.io?pullRequest=195) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/higress-group/higress-group.github.io?pullRequest=195) it.</sub>

2023-12-19 03:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/higress-group/higress-group.github.io?pullRequest=195) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/higress-group/higress-group.github.io?pullRequest=195) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/higress-group/higress-group.github.io?pullRequest=195) it.</sub>

2023-12-19 03:57 UTC, johnlanni requested changes

2023-12-19 03:57 UTC, johnlanni commented on i18n/zh-cn/docusaurus-plugin-content-blog/e2e-debug.md
> +## 起因
建议修改为背景说明，可以先介绍下本地的调试和端到端测试各自希望达到什么目的

2023-12-19 03:57 UTC, johnlanni commented on i18n/zh-cn/docusaurus-plugin-content-blog/e2e-debug.md
> +title: 在本地快速完成e2e测试并实现debug功能
标题可以改为：《教程：如何在本地进行higress调试和端到端测试》

2023-12-19 03:57 UTC, johnlanni commented on i18n/zh-cn/docusaurus-plugin-content-blog/e2e-debug.md
> +## 实现
内容结构上建议分为两部分：1.本地调试；2.端到端测试

2023-12-19 03:58 UTC, johnlanni commented
请 @CH3CHO  一并看看，给些建议

2023-12-19 04:42 UTC, sjcsjc123 commented
@johnlanni 已修改

2023-12-19 06:55 UTC, johnlanni approved these changes
Thanks, LGTM

2023-12-20 13:33 UTC, sjcsjc123 commented
It is ok.

2023-12-21 02:13 UTC, johnlanni commented
![image](https://github.com/higress-group/higress-group.github.io/assets/6763318/728352dc-d276-4a1f-817b-c8bca187897c)
这里可以加一篇，内容里面链接到这篇blog不

2023-12-21 02:38 UTC, sjcsjc123 commented
![image](https://github.com/higress-group/higress-group.github.io/assets/88550136/2ff51c11-d7c2-43f0-b95c-22a6a72668a3)
是这样吗，貌似不生效，想着让文档里的md能够完全展示出来blog里的内容。

2023-12-21 02:48 UTC, johnlanni commented
直接加个链接地址就行

2023-12-21 02:52 UTC, sjcsjc123 commented
已修改

2023-12-21 03:06 UTC, johnlanni requested changes

2023-12-21 03:06 UTC, johnlanni commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/dev/e2e-debug.md
> +title: 教程：如何在本地进行higress调试和端到端测试
做为开发者指南，标题名称建议改成<本地开发Debug指引>

2023-12-21 03:16 UTC, sjcsjc123 commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/dev/e2e-debug.md
> +title: 教程：如何在本地进行higress调试和端到端测试
已修改

2023-12-21 08:44 UTC, johnlanni approved these changes
LGTM

2023-12-21 09:12 UTC, johnlanni commented
![image](https://github.com/higress-group/higress-group.github.io/assets/6763318/e8b1525b-836c-4c57-9fac-e4a5e24681f0)
@sjcsjc123 CI失败了

2023-12-21 09:13 UTC, johnlanni commented
简单一些，用http链接也可以

2023-12-22 04:02 UTC, merged