doc: add ai-proxy plugin
higress-group/higress-group.github.io pull request #232
Opened 2024-05-20 14:31 UTC by cr7258

内容来自 ai-proxy 插件的 [README 文档](https://github.com/alibaba/higress/blob/main/plugins/wasm-go/extensions/ai-proxy/README.md), 在此基础上补充了 groq, claude 插件的文档，并在最后添加了完整的配置示例。

groq PR: https://github.com/alibaba/higress/pull/967
claude PR: https://github.com/alibaba/higress/pull/969

2024-05-20 14:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/higress-group/higress-group.github.io?pullRequest=232) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/higress-group/higress-group.github.io?pullRequest=232) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/higress-group/higress-group.github.io?pullRequest=232) it.</sub>

2024-05-20 14:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/higress-group/higress-group.github.io?pullRequest=232) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/higress-group/higress-group.github.io?pullRequest=232) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/higress-group/higress-group.github.io?pullRequest=232) it.</sub>

2024-05-21 09:48 UTC, CH3CHO requested changes

2024-05-21 09:48 UTC, CH3CHO commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/plugins/ai-proxy.md
> +```json
这个不是JSON吧。。。

2024-05-21 09:48 UTC, CH3CHO commented on sidebars.js
> +          items: ['plugins/intro', 'plugins/ai-proxy', 'plugins/custom', 'plugins/jwt-auth', 'plugins/hmac-auth', 'plugins/key-auth', 'plugins/basic-auth', 'plugins/key-rate-limit', 'plugins/custom-r
这里建议把 ai-proxy 放到 custom 后面

![image](https://github.com/higress-group/higress-group.github.io/assets/2909796/c3cc1c46-7f1b-4bed-b5ca-dca48a6ed38e)

2024-05-21 11:30 UTC, cr7258 commented on sidebars.js
> +          items: ['plugins/intro', 'plugins/ai-proxy', 'plugins/custom', 'plugins/jwt-auth', 'plugins/hmac-auth', 'plugins/key-auth', 'plugins/basic-auth', 'plugins/key-rate-limit', 'plugins/custom-r
ai-proxy和其他的插件有什么区别么？为什么要单独把它放在自定义插件里，其他的算是官方提供的插件？

2024-05-21 11:33 UTC, CH3CHO commented
不是放在自定义插件里面，是排在它的下面。因为自定义插件那一页是讲插件开发的。

| |
Kent Dong
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 05/21/2024 19:30 |
| To | ***@***.***> |
| Cc | Kent ***@***.***>,
Review ***@***.***> |
| Subject | Re: [higress-group/higress-group.github.io] doc: add ai-proxy plugin (PR #232) |

@cr7258 commented on this pull request.

In sidebars.js:

> @@ -34,7 +34,7 @@ const sidebars = {
         {
           type: 'category',
           label: 'Plugins',
-          items: ['plugins/intro', 'plugins/custom', 'plugins/jwt-auth', 'plugins/hmac-auth', 'plugins/key-auth', 'plugins/basic-auth', 'plugins/key-rate-limit', 'plugins/custom-response', 'plugins/bot-detect', 'plugins/request-block', 'plugins/waf'],
+          items: ['plugins/intro', 'plugins/ai-proxy', 'plugins/custom', 'plugins/jwt-auth', 'plugins/hmac-auth', 'plugins/key-auth', 'plugins/basic-auth', 'plugins/key-rate-limit', 'plugins/custom-response', 'plugins/bot-detect', 'plugins/request-block', 'plugins/waf'],


ai-proxy和其他的插件有什么区别么？为什么要单独把它放在自定义插件里，其他的算是官方提供的插件？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-05-21 11:36 UTC, cr7258 commented on sidebars.js
> +          items: ['plugins/intro', 'plugins/ai-proxy', 'plugins/custom', 'plugins/jwt-auth', 'plugins/hmac-auth', 'plugins/key-auth', 'plugins/basic-auth', 'plugins/key-rate-limit', 'plugins/custom-r
@CH3CHO  顺序调整好了

2024-05-21 11:36 UTC, cr7258 commented on sidebars.js
> +          items: ['plugins/intro', 'plugins/ai-proxy', 'plugins/custom', 'plugins/jwt-auth', 'plugins/hmac-auth', 'plugins/key-auth', 'plugins/basic-auth', 'plugins/key-rate-limit', 'plugins/custom-r
<img width="347" alt="image" src="https://github.com/higress-group/higress-group.github.io/assets/40051120/44ae0be1-5378-4524-8f9f-6a310a3ccd78">

2024-05-21 13:36 UTC, merged