feat: doc for building wasm-go
higress-group/higress-group.github.io pull request #97
Opened 2023-03-13 07:07 UTC by dspo

构建 wasm-go 的文档

2023-03-15 11:00 UTC, CH3CHO requested changes

2023-03-15 11:00 UTC, CH3CHO commented on i18n/en-us/docusaurus-plugin-content-docs/current/user/wasm-go.md
>  ## 1. Initialize the project
中文部分修改了，英文部分要对应进行调整吗？

2023-03-15 11:00 UTC, CH3CHO commented on docs/user/wasm-go.md
> +见 3.1; 如果你是使用自行初始化的目录，见 3.2.
这里为啥要换行？

2023-03-15 11:00 UTC, CH3CHO commented on docs/user/wasm-go.md
> +使用以下命令可以快速构建 wasm-go 插件:
中文部分建议使用中文标点。

2023-03-15 11:00 UTC, CH3CHO commented on docs/user/wasm-go.md
> +你也可以直接使用 `make build-push` 一并构建和推送 image.
建议使用中文标点

2023-03-15 11:00 UTC, CH3CHO commented on i18n/en-us/docusaurus-plugin-content-docs/current/user/wasm-go.md
> +### 1.2 create a new project yourself
这几个标题首字母是否应该都大写？另外，这里加上“yourself”感觉怪怪的。

2023-03-17 03:03 UTC, johnlanni approved these changes
LGTM

2023-03-17 03:03 UTC, johnlanni commented
@dspo  please resolve the conflicts

2023-03-20 09:12 UTC, CH3CHO approved these changes
OK

2023-03-20 09:12 UTC, merged